#! /usr/bin/bash

function validateArgument {                                                                                     # add function to validate DataBase_Name
    if [ -z "$1" ]
    then
        echo "The name field cannot be left empty"
        return 1
    elif [[ "$1" =~ ^[0-9] ]]
    then
        echo "Name should not begin with a number"
        return 1
    elif [[ "$1" = *" "* ]]
    then
      echo "Name Shouldn't Have Spaces"
        return 1
    elif [[ "$1" =~ [^a-zA-Z0-9_] ]]
    then
        echo "Name Shouldn't Have Special Characters"
        return 1
    fi
    
}

echo "Hello in your database managment system what would you like to do: "
select command in CreateDB ListDatabases ConnectToDatabases DropDatabase exit
do
case $command in 
"1" | "CreateDB" )
	while true
    do
    read -p "Enter the name of database you want to create: " dirname 
	validateArgument $dirname                                                     # write fun validtion and db_name
	 dirname=$(echo "$dirname" | tr ' ' '_')                                                     # replace space with (_)
     
        if [ $? -eq 0 ]                                                            # check if command successed will be exit 
        then
            break
        fi
    done
        if [ -e $dirname ]
        then
            echo "database already exists!"
        else
            mkdir "$dirname"
            echo "Database created successfully."
    fi
    ;;

"ListDatabases")
    DBS=$(ls -l | grep ^d | cut -d " " -f 9)
    if [[ $DBS ]]
    then
        echo ${DBS}
    else
        echo "No databases exists."
    fi
    ;;
"ConnectToDatabases")
    read -p "Which database would you like to connect to?" dbs
    if [ -e $dbs ]
    then 
        cd $dbs
        echo "Connected to Database "${dbs}
    else
        echo "Database doesn't exist."
    fi
    ;;
"DropDatabase")
    read -p "Enter the name of database you would like to delete: " dbs
    if [ -e $dbs ]
    then
        read -p "Are you sure you want to delete $dbs database! (y/n): " ans
        if [ $ans == "y" ]
        then
            rm -r ${dbs}
            echo "Database $dbs has been deleted sucessfully."
        else
            echo "Deletion cancelled. Nothing deleted."
        fi
    else
        echo "Database doesn't exists."
    fi
    ;;
"exit")
    echo "Exiting..."
    break
    ;;
esac
done
