#! /bin/bash

connectedDbs=$1
# Function to validate the database name argument
function validateArgument {
    if [ -z "$1" ]
    then
        echo "The name field cannot be left empty"
        return 1
    elif [[ "$1" =~ ^[0-9] ]]
    then
        echo "Name should not begin with a number"
        return 1
    elif [[ "$1" = *" "* ]]
    then
        echo "Name Shouldn't Have Spaces"
        return 1
    elif [[ "$1" =~ [^a-zA-Z0-9_] ]]
    then
        echo "Name Shouldn't Have Special Characters"
        return 1
    fi
}

createTable(){
    local db_dir="$connectedDbs"
    local tablename
    local col_name
    local col_type
    local is_pk
    local add_more
    local pk_col

    read -p "Enter the name of the table: " tablename
    tablename=$(echo "$tablename" | tr ' ' '_')

    if [[ ! "$tablename" =~ ^[a-zA-Z][a-zA-Z0-9_]*$ ]]; then
        echo "Invalid table name. It should start with a letter and contain only letters, numbers, and underscores."
        return
    fi

    if [ -e ./"$db_dir/$tablename" ]; then
        echo "Table already exists!"
        return
    fi

    touch ./"$db_dir/$tablename"
    touch ./"$db_dir/$tablename.meta"

    pk_col=""

    while true; do
        read -p "Enter the name of the column: " col_name
        col_name=$(echo "$col_name" | tr ' ' '_')
        if [[ ! "$col_name" =~ ^[a-zA-Z][a-zA-Z0-9_]*$ ]]; then
            echo "Invalid column name. It should start with a letter and contain only letters, numbers, and underscores."
            continue
        fi

        read -p "Enter the datatype of the column (int/string): " col_type
        if [[ "$col_type" != "int" && "$col_type" != "string" ]]; then
            echo "Invalid datatype. Please enter 'int' or 'string'."
            continue
        fi

        

        read -p "Is $col_name a primary key? (yes/no): " is_pk
        if [[ "$is_pk" != "yes" && "$is_pk" != "no" ]]; then
            echo "Invalid option. Please enter 'yes' or 'no'."
            continue
        fi

        if [[ "$is_pk" == "yes" ]]; then
            if [[ -n "$pk_col" ]]; then
                echo "A primary key already exists. Only one primary key is allowed."
                continue
            else
                pk_col=$col_name
				echo "$col_name:$col_type" >> ./"$db_dir/$tablename.meta"
                sed -i "/primary_key/d" ./"$db_dir/$tablename.meta"
                echo "primary_key:$pk_col" >> ./"$db_dir/$tablename.meta"
            fi
		else
				echo "$col_name:$col_type" >> ./"$db_dir/$tablename.meta"
        fi

		 while true; do
            read -p "Do you want to add more columns? (yes/no): " add_more
            case "$add_more" in
                yes)
                    break
                    ;;
                no)
                    echo "Finished adding columns."
					echo "Table $tablename created successfully."
                    return
                    ;;
                *)
                    echo "Invalid option. Please enter 'yes' or 'no'."
                    ;;
            esac
        done
    done
}
selectFromTable(){                                   #function to select from Table  
	local tablename 
	local col_name
    
    if [ -z "$(ls)" ]
    then
        echo "No Tables To Select From, Table Is Empty."
        return
    fi
    
    while true
    do
        read -p "Enter Table Name: " tablename
        validateArgument $tablename
        if [ $? -eq 0 ]
        then
            break
        fi
    done
    
    if [ ! -d "$tablename" ]
    then
        echo "Table Doesn't Exist"
        return
    fi
    
    if [ -s "$tablename/$$tableName.txt" ]
    then
        echo "The $tablename is empty."
        return
    fi
    
    tail -1 ${tablename}/${tablename}-meta.txt | sed 's/:/\t/g'
    sed 's/:/\t/g'  ${tablename}/${tablename}.txt && echo
    
}

DropTable(){
	read -p "Enter the name of the table you want to drop: " tablename
	if [ -z $tablename ]
	then
		echo "Empty input."
	else
		if [ -f ./"$connectedDbs/$tablename" ]; then
			rm ./"$connectedDbs/$tablename"
			echo "Table '$tablename' has been deleted successfully."
		else
			echo "Table '$tablename' does not exist."
		fi
	fi
}
listTables(){
	output=$(ls ./$connectedDbs)
		if [[ $output ]]
		then
			echo $output
		else
			echo "No tables exists yet. "
		fi
}
UpdateTable(){
echo "update"
}
DeleteFromTable(){
echo "delete"
}

echo "Hello in your $connectedDbs database what would you like to do: "
select command in CreateTable ListTables DropTable InsertIntoTables SelectFromTable UpdateTable DeleteFromTable QuitFromDB
do
case $command in 
"CreateTable" )
		createTable
    ;;
"ListTables")
		listTables
;;
"DropTable")
		DropTable
	
	;;
"InsertIntoTables")
	insertIntoTable
;;

"SelectFromTable")
   		selectFromTable
;;

"UpdateTable")
		UpdateTable

;;
"DeleteFromTable ")
		DeleteFromTable
;;
"QuitFromDB")
	echo "Exiting from $connectedDbs database. "
	break 
;;
*)
echo "Invalid Selection"
esac
done
