#! /bin/bash

connectedDbs=$1

# function to create table
createTable(){
	local db_dir="$connectedDbs"
    local tablename
    local col_name
    local col_type
    local is_pk
    local add_more
    local pk_col

    read -p "Enter the name of the table: " tablename
    tablename=$(echo "$tablename" | tr ' ' '_')

    if [[ ! "$tablename" =~ ^[a-zA-Z][a-zA-Z0-9_]*$ ]]; then
        echo "Invalid table name. It should start with a letter and contain only letters, numbers, and underscores."
        return
    fi

    if [ -e ./"$db_dir/$tablename" ]; then
        echo "Table already exists!"
        return
    fi

    touch ./"$db_dir/$tablename"
    touch ./"$db_dir/$tablename.meta"

    pk_col=""

    while true; do
        read -p "Enter the name of the column: " col_name
        col_name=$(echo "$col_name" | tr ' ' '_')
        if [[ ! "$col_name" =~ ^[a-zA-Z][a-zA-Z0-9_]*$ ]]; then
            echo "Invalid column name. It should start with a letter and contain only letters, numbers, and underscores."
            continue
        fi

        read -p "Enter the datatype of the column (int/string): " col_type
        if [[ "$col_type" != "int" && "$col_type" != "string" ]]; then
            echo "Invalid datatype. Please enter 'int' or 'string'."
            continue
        fi

        

        read -p "Is $col_name a primary key? (yes/no): " is_pk
        if [[ "$is_pk" != "yes" && "$is_pk" != "no" ]]; then
            echo "Invalid option. Please enter 'yes' or 'no'."
            continue
        fi

        if [[ "$is_pk" == "yes" ]]; then
            if [[ -n "$pk_col" ]]; then
                echo "A primary key already exists. Only one primary key is allowed."
                continue
            else
                pk_col=$col_name
				echo "$col_name:$col_type" >> ./"$db_dir/$tablename.meta"
                sed -i "/primary_key/d" ./"$db_dir/$tablename.meta"
                echo "primary_key:$pk_col" >> ./"$db_dir/$tablename.meta"
            fi
		else
				echo "$col_name:$col_type" >> ./"$db_dir/$tablename.meta"
        fi

		 while true; do
            read -p "Do you want to add more columns? (yes/no): " add_more
            case "$add_more" in
                yes)
                    break
                    ;;
                no)
                    echo "Finished adding columns."
					echo "Table $tablename created successfully."
                    return
                    ;;
                *)
                    echo "Invalid option. Please enter 'yes' or 'no'."
                    ;;
            esac
        done
    done
}


# Function to insert data into the table
insertIntoTable() {
    local db_dir="$connectedDbs"
    local tablename
    local table_file
    local schema_file
    local col_names=()
    local col_types=()
    local pk_col
    local data
    local pk_value
    local valid

    read -p "Enter the name of the table to insert into: " tablename
    tablename=$(echo "$tablename" | tr ' ' '_')

    table_file="$db_dir/$tablename"
    schema_file="$db_dir/$tablename.meta"

    if [ ! -e "$table_file" ]; then
        echo "Table does not exist!"
        return
    fi

     while IFS=: read col_name col_type; do

        # Handle primary key
        if [[ "$col_name" == primary_key* ]]; then
            pk_col=$col_type
        else
            col_names+=("$col_name")
            col_types+=("$col_type")
        fi
    done < "$schema_file"

    # Prompt user for data
    while true; do
        data=()
        valid=true
        
        for i in "${!col_names[@]}"; do
            read -p "Enter value for ${col_names[$i]} (${col_types[$i]}): " value
            
            # Validate data
            case "${col_types[$i]}" in
                int)
					if [[ $((value)) != $value ]]; then
					        echo "Error: Value '$value' is not a valid integer for column '${col_names[$i]}'."
                    		valid=false
                    		break
					fi
                    ;;
                string)
                    if [ -z $value ]
                    then
                        echo "empty input,try again."
                        valid=false
                        break
                    else
                        if [[ ! $value =~ [a-zA-Z]* ]]
                        then
                            echo "invalid string."
                            valid=false
                            break
                        fi
                    fi
                    ;;
                *)
                    echo "Error: Unknown data type '${col_types[$i]}' for column '${col_names[$i]}'."
                    valid=false
                    break
                    ;;
            esac
            record+=("$value")
        done
        echo ${data[@]}

        if [ "$valid" = true ]; then
            # Check if primary key value is unique
            if [[ -n "$pk_col" ]]; then
                echo "${col_names[@]}"
                pk_index=$(echo "${col_names[@]}" | tr ' ' '\n' | grep -n "^$pk_col$" | cut -d: -f1)

                pk_value="${record[$((pk_index - 1))]}"

                echo "Checking for primary key value: $pk_col:$pk_value"

                if grep "${pk_col}:${pk_value}" "$table_file"; then
                    echo "Error: Primary key value '$pk_value' already exists."
                    continue
                fi
            fi

            line=""
            for i in "${!col_names[@]}"
            do
                line+="${col_names[$i]}:${record[$i]},"
            done

            # Remove the trailing comma
            line=${line%,}
            echo "$line"
            echo "$line" >> "$table_file"
            
            echo "Data inserted successfully."
        fi

        read -p "Do you want to insert more rows? (yes/no): " more
        if [[ "$more" != "yes" ]]; then
            echo "Finished inserting rows."
            return
        fi
    done
}

deleteFromTable() {
    local db_dir="$connectedDbs"
    local table_file
    local schema_file
    local col_names=()
    local col_types=()
    local pk_col
    local value
    local pk_value

    tablename=""
    read -p "Enter the name of the table to delete from: " tablename
    tablename=$(echo "$tablename" | tr ' ' '_')

    table_file="$db_dir/$tablename"
    schema_file="$db_dir/$tablename.meta"

    # Check if table exists
    if [ -z "$tablename" ]
    then
        echo "Empty input"
        return
    fi
    if [ ! -e "$table_file" ]; then
        echo "Table does not exist!"
        return
    fi

    # Read schema file and determine the columns and types
    while IFS=: read col_name col_type; do
        if [[ "$col_name" =~ primary_key* ]]; then
            pk_col="${col_type}"
        else
            col_names+=("$col_name")
            col_types+=("$col_type")
        fi
    done < "$schema_file"

    # Display menu options
    echo "Select deletion option:"
    echo "1) Delete by ID (Primary Key)"
    echo "2) Delete by Column"
    echo "3) Delete All Rows"
    read -p "Enter your choice (1/2/3): " delete_option

    case "$delete_option" in
    1)
        # Delete by ID (Primary Key)
        if [[ -z "$pk_col" ]]; then
            echo "Error: No primary key defined for this table."
            return
        fi
        
        read -p "Enter the primary key value to delete: " pk_value

        deletedRow="$pk_col:$pk_value"
        tableFile="./$connectedDbs/$tablename"

        grep "$deletedRow" $tableFile
        if [ $? == 1 ]; then
            echo "No matching rows found to delete."
            return
        fi

        sed -i "/$deletedRow/d" "$tableFile"        
        echo "Matching rows has been Deleted."
        ;;
    2)
        read -p "Enter the column name to filter by: " column_name

        if ! [[ " ${col_names[@]} " =~ " $column_name " ]]; then
                echo "Error: Column '$column_name' does not exist."
                return
        fi

        read -p "Enter the value to filter by: " value

        column_index=$(echo "${col_names[@]}" | tr ' ' '\n' | grep -n "^$column_name$" | cut -d: -f1)
        column_index=$((column_index - 1))
        column_type="${col_types[$column_index]}"

        case "$column_type" in
            int)
                if ! [[ "$value" =~ ^[0-9]+$ ]]; then
                    echo "Error: Value for column '$column_name' must be an integer."
                    return
                fi
                ;;
            string)
                if [[ -z "$value" ]]; then
                    echo "Error: Value for column '$column_name' must not be empty."
                    return
                fi
                ;;
            *)
                echo "Error: Unknown data type for column '$column_name'."
                return
                ;;
        esac


        deletedRow="$column_name:$value"
        tableFile="./$connectedDbs/$tablename"
        
        grep "$deletedRow" $tableFile
        if [ $? == 1 ]; then
            echo "No matching rows found to delete."
            return
        fi

        sed -i "/$deletedRow/d" "$tableFile"        
        echo "Matching rows has been Deleted."
    ;;
    3)
        > "$table_file"
        echo "All rows have been deleted."
        return
        ;;
    *)
        echo "Invalid option selected."
        return
        ;;
    esac
}

echo "Hello in your $connectedDbs database what would you like to do: "
select command in CreateTable ListTables DropTable InsertIntoTables SelectFromTable UpdateTable DeleteFromTable QuitFromDB
do
case $command in 
"CreateTable" )
	createTable
    ;;
"ListTables")
		output=$(ls ./$connectedDbs)
		if [[ $output ]]
		then
			echo $output
		else
			echo "No tables exists yet. "
		fi
;;
"DropTable")
	read -p "Enter the name of the table you want to drop: " tablename
	if [ -z $tablename ]
	then
		echo "Empty input."
	else
		if [ -f ./"$connectedDbs/$tablename" ]; then
			rm ./"$connectedDbs/$tablename"
			echo "Table '$tablename' has been deleted successfully."
		else
			echo "Table '$tablename' does not exist."
		fi
	fi
	;;
"InsertIntoTables")
	insertIntoTable
;;

"SelectFromTable")
;;

"UpdateTable")

;;
"DeleteFromTable")
    deleteFromTable
;;
"QuitFromDB")
	echo "Exiting from $connectedDbs database. "
	break 
;;
*)
echo "Invalid Selection"
esac
done
